# 1.HOW TO CREATE SCREEN.. 
# 2.CREATE AND MOVE THE PADDLE..
# 3.CREATE ANOTHER PADDLE SO THAT IT IS A 2PLAYER GAME..
# 4.CREATE THE BALL AND MAKE IT MOVE THE BALL .
# 5. DETECT COLLISION WITH BALL AND BOUNCE BACK
# 6 DETECT COLLISION WITH PADDLE
# 7. DETECT WHEN THE PADDLE MISSES
# 8. KEEP SCORE