# ATTRIBUTE IS JUST A FANCY NAME FOR A VARIBALE THAT IS ASSOCIATED WITH A OBJECT EG FOR WAITER 
# IS_HOLDING_PLATE = TRUE THIS IS CALLED A ATTRIBUTE ... attributes are the things object  has

# MODEL IS ANOTHER NAME FOR FUNCTION BECAUSE IT IS ASSOCIATED WITH THE MAIN PART, WAITER
# DEF TAKE_ORDER(ORDER,TABLE) ,, DEF TAKE_PAYMENT(AMOUNT...methods are the things object can do

# WAITER CAN HAVE MULTIPLE ENTITES UNDER THEM EG HENRY , SIYA ETC
# SO WE CALL WAITER AS A CLASS AND ENTITIES INSIDE IT AS OBJECT..

